name: 'Z-Wave Lock BP'
packageKey: 'zwave-lock-bp'
permissions:
  zwave: {}
description: "BP-enhanced SmartThings driver for Z-Wave lock devices"
vendorSupportInformation: "https://support.smartthings.com"
